theme: jekyll-theme-minimal
title: John Brown Belt Club
description: A community funded martial arts and self defense scholarship for our BIPOC neighbors
logo: https://github.com/saouderkirk/john_brown_belt_club/blob/gh-pages/JohnBrownBeltClubLogo.png
